name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - { name: "ImmortalWRT", url: "https://github.com/immortalwrt/immortalwrt", branch: "master" }
          - { name: "IStoreOS", url: "https://github.com/istoreos/istoreos", branch: "main" }
          - { name: "LEDE", url: "https://github.com/coolsnowwolf/lede", branch: "master" }

    steps:
    - name: Checkout repository
      run: |
        echo "Checking updates for ${{ matrix.repo.name }}"
        git clone --depth 1 ${{ matrix.repo.url }} -b ${{ matrix.repo.branch }} repo
        cd repo
        commitHash=$(git rev-parse HEAD)
        echo "commitHash=$commitHash" >> $GITHUB_ENV

    - name: Download Previous Commit Hash
      id: download
      uses: actions/cache@v3
      with:
        path: .commitHash_${{ matrix.repo.name }}
        key: commitHash-${{ matrix.repo.name }}

    - name: Check Previous Commit Hash
      id: check
      run: |
        if [ -f .commitHash_${{ matrix.repo.name }} ]; then
          oldHash=$(cat .commitHash_${{ matrix.repo.name }})
          echo "oldHash=$oldHash"
        else
          oldHash=""
        fi
        echo "oldHash=$oldHash" >> $GITHUB_ENV

    - name: Compare and Save New Commit Hash
      id: compare
      run: |
        if [ "$oldHash" != "$commitHash" ]; then
          echo "New commit detected for ${{ matrix.repo.name }}"
          echo $commitHash > .commitHash_${{ matrix.repo.name }}
          echo "updated=true" >> $GITHUB_ENV
        else
          echo "No updates for ${{ matrix.repo.name }}"
          echo "updated=false" >> $GITHUB_ENV
        fi

    - name: Upload New Commit Hash
      if: env.updated == 'true'
      uses: actions/cache@v3
      with:
        path: .commitHash_${{ matrix.repo.name }}
        key: commitHash-${{ matrix.repo.name }}

    - name: Trigger build
      if: env.updated == 'true'
      uses: peter-evans/repository-dispatch@main
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: "Source Code Update for ${{ matrix.repo.name }}"

    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 3
        keep_minimum_runs: 3
